"""Rebuild search-index.json and the index.html section tiles from the card pages.

Run from the repo root:  python tools/build_index.py

- Every <div class="module-card" id=.. data-tags=..> on a content page becomes an index entry.
- Existing entries keep their hand-curated "text" (matched by id+file, then by id if the card moved).
- New cards get text auto-extracted from the card body.
- Non-card entries (AI, CHEAT) are preserved.
"""
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKIP = {'index.html', 'pardha_rf_complete_backup.html'}
DIV = re.compile(r'<div\b|</div>')
CARD = re.compile(r'<div class="module-card[^"]*" id="([^"]+)" data-tags="([^"]*)"')
TITLE = re.compile(r'<span class="mod-title">(.*?)</span>', re.S)

# Section tiles on index.html: (group heading, [(file, tile name, example topics)])
TILES = [
    ('Learn RF — by level', [
        ('foundation.html', 'Foundation', 'Signal path, ADC, RSSI, FHGW, kTB'),
        ('beginner.html', 'Beginner', 'dB, 50 Ω, RF chain, metrics, OFDM, ACLR, PRACH'),
        ('intermediate.html', 'Intermediate', 'AAU architecture, RFFE, PA efficiency, gain budget'),
        ('expert.html', 'Expert', 'Noise, PA/DPD, MIMO, sync, calibration, RCA'),
    ]),
    ('RCT, RU & O-RAN', [
        ('features.html', 'RCT Features', 'Conformance tests, automation traces, uSleep, DSA, calibration'),
        ('common-features.html', 'Common (RU / BBU / O-RAN)', 'M-plane, carrier activation, power, firmware, sync'),
        ('instruments.html', 'Instruments', 'EXA, EXM, VNA, bench setup, AAU LEDs'),
    ]),
    ('LTE, 5G & Protocol', [
        ('protocol.html', 'Protocol', 'Layers, channels, call flows, interfaces, CSI, EPC'),
        ('lte-features.html', 'LTE Features', 'CA, X2/S1 HO, DRX, VoLTE, CSFB, CMAS/ETWS'),
        ('nr-sa-features.html', '5G SA Features', 'Bring-up, Xn/N2/DU/CU HO, MIMO, VoNR'),
        ('nr-nsa-features.html', '5G NSA Features', 'EN-DC, SgNB addition, split bearer'),
        ('protocol_debug.html', 'Protocol Debug', 'Layer debug, timers, RLF, captures, playbook'),
        ('notes.html', 'Study Notes', 'Chapter notes: 5G, LTE, SIBs, HO, KPIs'),
    ]),
    ('Lab, Automation & Career', [
        ('automation.html', 'Automation', 'Python, pytest, Robot, SCPI, watchdogs'),
        ('docs.html', 'Docs & Videos', 'Test plans, decks, learning path, videos'),
        ('resume.html', 'Resume / UE tools', 'QXDM, ADB, TM500, Amarisoft, KPI testing'),
        ('interview.html', 'Interview', 'Question bank + real debriefs'),
        ('cheatsheet.html', 'Cheat Sheet', 'Formulas, tables, flows, traps'),
    ]),
]


def card_blocks(s):
    for m in CARD.finditer(s):
        d = 0
        for t in DIV.finditer(s, m.start()):
            d += -1 if t.group() == '</div>' else 1
            if d == 0:
                yield m.group(1), m.group(2), s[m.start():t.end()]
                break


def plain(fragment):
    txt = re.sub(r'<(script|style|svg)\b.*?</\1>', ' ', fragment, flags=re.S)
    txt = re.sub(r'<[^>]+>', ' ', txt)
    return re.sub(r'\s+', ' ', html.unescape(txt)).strip()


def main():
    idx_path = ROOT / 'search-index.json'
    old = json.loads(idx_path.read_text(encoding='utf-8'))
    by_key = {(e['id'], e['file']): e for e in old}
    by_id = {}
    for e in old:
        by_id.setdefault(e['id'], []).append(e)

    new, counts, seen = [], {}, set()
    for page in sorted(ROOT.glob('*.html')):
        if page.name in SKIP:
            continue
        s = page.read_text(encoding='utf-8')
        n = 0
        for cid, tags, block in card_blocks(s):
            n += 1
            tm = TITLE.search(block)
            title = plain(tm.group(1)) if tm else cid
            prev = by_key.get((cid, page.name))
            if prev is None:
                # moved card: same id, its old file no longer holds it
                for e in by_id.get(cid, []):
                    if f'id="{cid}"' not in (ROOT / e['file']).read_text(encoding='utf-8'):
                        prev = e
                        break
            text = prev['text'] if prev else plain(block)[:700]
            new.append({'id': cid, 'title': title, 'file': page.name, 'tags': tags, 'text': text})
            seen.add((cid, page.name))
        if n:
            counts[page.name] = n

    # keep non-card entries (AI page, cheat sheet, ...)
    for e in old:
        if e['file'] not in counts and (e['id'], e['file']) not in seen:
            new.append(e)

    idx_path.write_text(json.dumps(new, ensure_ascii=False, separators=(',', ':')), encoding='utf-8')

    # index.html tiles
    parts = ['<!-- TILES:START (generated by tools/build_index.py) -->']
    for heading, tiles in TILES:
        parts.append(f'<div class="tile-group">{heading}</div>\n<div class="sec-tiles">')
        for f, name, eg in tiles:
            c = counts.get(f)
            cnt = f'{c} cards' if c else 'page'
            parts.append(f'  <a class="sec-tile" href="{f}">\n    <div class="st-name">{name}</div>\n'
                         f'    <div class="st-count">{cnt}</div>\n    <div class="st-eg">{eg}</div>\n  </a>')
        parts.append('</div>')
    total = sum(counts.values())
    parts.append(f'<div style="text-align:center;color:#4a5470;font-size:11px;padding:24px">RF Lab Guide · {total} cards · '
                 'offline-ready PWA · fallback: <a href="pardha_rf_complete_backup.html" style="color:#5bc4ef">single-file version</a></div>')
    parts.append('<!-- TILES:END -->')
    ip = ROOT / 'index.html'
    s = ip.read_text(encoding='utf-8')
    s, k = re.subn(r'<!-- TILES:START.*?<!-- TILES:END -->', lambda _: '\n'.join(parts), s, flags=re.S)
    if not k:
        sys.exit('TILES markers not found in index.html')
    ip.write_text(s, encoding='utf-8', newline='\n')

    print(f'{len(new)} index entries, {total} cards')
    for f, c in counts.items():
        print(f'  {f:24} {c}')


if __name__ == '__main__':
    main()
